hiz = int(input("Lütfen 25 dakikada çözebileceğiniz sayfa miktarını yazınız: "))
sayfa = int(input("Lütfen yapmanız gereken sayfa sayısını giriniz:"))
zaman = int((sayfa / hiz)*25)
kere_calisma = round(sayfa / hiz)
print("Sizin için en uygun düzeni yapmaya çalıştık")
print("Sonuçlar:")
print("-------------------------")
print(" ")
print("{0} kere 25 dakikalık çalışma yapınız".format(kere_calisma))
print("toplam {0} dakika".format(zaman))
print("-------------------------")
print(" ")
print("Başarılı bir çalışma için kendinize hedefler belirleyin ve bu hedeflere ulaşmak için planlı bir şekilde çalışın. Her 25 dakikalık çalışma sonrası 5 dakikalık bir mola vererek zihninizin dinlenmesine ve yenilenmesine yardımcı olabilirsiniz. Kendinize ödüller belirleyerek motivasyonunuzu yüksek tutun. Başarıya giden yolda size yardımcı olmak için buradayız, başarılar dileriz!")